
import os
import pandas as pd

csv_src = "/home/ainedineen/blurry_vision/pytorch_untrained_models/imagenet/fit_receptive_field/rf_model_params"


# generated by: python fit_rfs_23222_loop.py
filename = "supRN50_conv1_21_g0_60e_e60_rf_model_params.csv"

# for filename in os.listdir(csv_src):

# filename = "supRN50_conv1_21_g4_60e_e60_rf_model_params.csv"
print(filename)

# remove file suffix
model_name = os.path.splitext(filename)[0]
print(model_name)

file = os.path.join(csv_src, filename)

# load csv
df = pd.read_csv(file, index_col=None, header=0)
print(df.columns)
print(df.count())
# print(df['best_model'=='gab'].count())
print(df[['gabor_sigma', 'best_model' ]].groupby("best_model").mean())
# dog 29 
# sig1: 2.368501, sig2 = 18.501044
# gab 35
# gabor_sigma: 3.547933

gab_df = df.loc[df['best_model'] == 'gab']
print(len(gab_df))
print(gab_df['gabor_sigma'].mean()) 
print(gab_df['gabor_sigma'].std()) 

dog_df = df.loc[df['best_model'] == 'dog']
print(len(dog_df))
print(dog_df['dog_sig1'].mean())
print(dog_df['dog_sig1'].std())



# Create a csv file with model_name, dog_count, gab_count, dog_sig1_mean, gabor_sigma_mean
